from dataclasses import dataclass
from datetime import datetime
from typing import Literal

AuditEventType = Literal[
    "USER_LOGIN",
    "USER_LOGOUT",
    "AUTH_FAILED",
    "PROJECT_CREATED",
    "PROJECT_MEMBER_ADDED",
    "PROJECT_MEMBER_REMOVED",
    "PROJECT_MEMBER_ROLE_CHANGED",
    "BASELINE_POLICY_SNAPSHOT_SEEDED",
    "PROJECT_BASELINE_POLICY_ATTACHED",
    "AUDIT_LOG_VIEWED",
    "AUDIT_EVENT_VIEWED",
    "MY_ACTIVITY_VIEWED",
    "OUTBOUND_CALL_BLOCKED",
    "EXPORT_STUB_ROUTE_ACCESSED",
    "ADMIN_SECURITY_STATUS_VIEWED",
    "ACCESS_DENIED",
    "JOB_LIST_VIEWED",
    "JOB_RUN_CREATED",
    "JOB_RUN_STARTED",
    "JOB_RUN_FINISHED",
    "JOB_RUN_FAILED",
    "JOB_RUN_CANCELED",
    "JOB_RUN_VIEWED",
    "JOB_RUN_STATUS_VIEWED",
    "DOCUMENT_LIBRARY_VIEWED",
    "DOCUMENT_DETAIL_VIEWED",
    "DOCUMENT_TIMELINE_VIEWED",
    "DOCUMENT_UPLOAD_STARTED",
    "DOCUMENT_STORED",
    "DOCUMENT_SCAN_STARTED",
    "DOCUMENT_UPLOAD_CANCELED",
    "DOCUMENT_SCAN_PASSED",
    "DOCUMENT_SCAN_REJECTED",
    "DOCUMENT_IMPORT_FAILED",
    "DOCUMENT_PAGE_EXTRACTION_STARTED",
    "DOCUMENT_PAGE_EXTRACTION_COMPLETED",
    "DOCUMENT_PAGE_EXTRACTION_FAILED",
    "DOCUMENT_PAGE_EXTRACTION_RETRY_REQUESTED",
    "DOCUMENT_PROCESSING_RUN_VIEWED",
    "DOCUMENT_PROCESSING_RUN_STATUS_VIEWED",
    "PREPROCESS_OVERVIEW_VIEWED",
    "PREPROCESS_QUALITY_VIEWED",
    "PREPROCESS_RUNS_VIEWED",
    "PREPROCESS_ACTIVE_RUN_VIEWED",
    "PREPROCESS_RUN_VIEWED",
    "PREPROCESS_RUN_STATUS_VIEWED",
    "PREPROCESS_RUN_CREATED",
    "PREPROCESS_RUN_STARTED",
    "PREPROCESS_RUN_FINISHED",
    "PREPROCESS_RUN_FAILED",
    "PREPROCESS_RUN_CANCELED",
    "PREPROCESS_RUN_ACTIVATED",
    "PREPROCESS_COMPARE_VIEWED",
    "PREPROCESS_VARIANT_ACCESSED",
    "TRANSCRIPTION_OVERVIEW_VIEWED",
    "TRANSCRIPTION_TRIAGE_VIEWED",
    "TRANSCRIPTION_TRIAGE_ASSIGNMENT_UPDATED",
    "TRANSCRIPTION_RUN_CREATED",
    "TRANSCRIPTION_RUN_STARTED",
    "TRANSCRIPTION_RUN_FINISHED",
    "TRANSCRIPTION_RUN_FAILED",
    "TRANSCRIPTION_RUN_CANCELED",
    "TRANSCRIPTION_RUN_VIEWED",
    "TRANSCRIPTION_RUN_STATUS_VIEWED",
    "TRANSCRIPTION_ACTIVE_RUN_VIEWED",
    "TRANSCRIPTION_RUN_ACTIVATED",
    "TRANSCRIPTION_WORKSPACE_VIEWED",
    "TRANSCRIPT_LINE_CORRECTED",
    "TRANSCRIPT_EDIT_CONFLICT_DETECTED",
    "TRANSCRIPT_DOWNSTREAM_INVALIDATED",
    "TRANSCRIPT_VARIANT_LAYER_VIEWED",
    "TRANSCRIPT_ASSIST_DECISION_RECORDED",
    "APPROVED_MODEL_LIST_VIEWED",
    "APPROVED_MODEL_CREATED",
    "PROJECT_MODEL_ASSIGNMENT_CREATED",
    "MODEL_ASSIGNMENT_LIST_VIEWED",
    "MODEL_ASSIGNMENT_DETAIL_VIEWED",
    "TRAINING_DATASET_VIEWED",
    "PROJECT_MODEL_ACTIVATED",
    "PROJECT_MODEL_RETIRED",
    "LAYOUT_OVERVIEW_VIEWED",
    "LAYOUT_TRIAGE_VIEWED",
    "LAYOUT_RUNS_VIEWED",
    "LAYOUT_ACTIVE_RUN_VIEWED",
    "LAYOUT_RUN_CREATED",
    "LAYOUT_RUN_ACTIVATED",
    "LAYOUT_RUN_STARTED",
    "LAYOUT_RUN_FINISHED",
    "LAYOUT_RUN_FAILED",
    "LAYOUT_RUN_CANCELED",
    "LAYOUT_ACTIVATION_BLOCKED",
    "LAYOUT_RECALL_STATUS_VIEWED",
    "LAYOUT_RESCUE_CANDIDATES_VIEWED",
    "LAYOUT_OVERLAY_ACCESSED",
    "LAYOUT_PAGEXML_ACCESSED",
    "LAYOUT_LINE_ARTIFACTS_VIEWED",
    "LAYOUT_LINE_CROP_ACCESSED",
    "LAYOUT_CONTEXT_WINDOW_ACCESSED",
    "LAYOUT_THUMBNAIL_ACCESSED",
    "LAYOUT_READING_ORDER_UPDATED",
    "LAYOUT_EDIT_APPLIED",
    "LAYOUT_DOWNSTREAM_INVALIDATED",
    "PAGE_METADATA_VIEWED",
    "PAGE_IMAGE_VIEWED",
    "PAGE_THUMBNAIL_VIEWED",
    "OPERATIONS_OVERVIEW_VIEWED",
    "OPERATIONS_SLOS_VIEWED",
    "OPERATIONS_ALERTS_VIEWED",
    "OPERATIONS_TIMELINE_VIEWED",
]


@dataclass(frozen=True)
class AuditRequestContext:
    request_id: str
    method: str
    route_template: str
    path: str
    ip: str | None
    user_agent: str | None


@dataclass(frozen=True)
class AuditEventRecord:
    id: str
    chain_index: int
    timestamp: datetime
    actor_user_id: str | None
    project_id: str | None
    event_type: AuditEventType
    object_type: str | None
    object_id: str | None
    ip: str | None
    user_agent: str | None
    request_id: str
    metadata_json: dict[str, object]
    prev_hash: str
    row_hash: str


@dataclass(frozen=True)
class AuditIntegrityStatus:
    checked_rows: int
    chain_head: str | None
    is_valid: bool
    first_invalid_chain_index: int | None
    first_invalid_event_id: str | None
    detail: str
