var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(authenticated)/projects/[projectId]/documents/[documentId]/retry-extraction/route.js")
R.c("server/chunks/[root-of-the-server]__f4e1e429._.js")
R.c("server/chunks/web_lib_data_api-client_ts_e0ef38f9._.js")
R.c("server/chunks/web_lib_routes_ts_62a4279b._.js")
R.c("server/chunks/_a0e427fd._.js")
R.c("server/chunks/[root-of-the-server]__f3948257._.js")
R.c("server/chunks/web_lib_documents_ts_a2fa8b7f._.js")
R.c("server/chunks/92726_[projectId]_documents_[documentId]_retry-extraction_route_actions_7297e0a4.js")
R.m(62506)
module.exports=R.m(62506).exports
