// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(authenticated)/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/audit/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit/[eventId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/audit/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/capacity/tests/[testRunId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/capacity/tests/[testRunId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/capacity/tests/[testRunId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/capacity/tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/capacity/tests">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/capacity/tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/design-system">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/index-quality/[indexKind]/[indexId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/index-quality/[indexKind]/[indexId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/index-quality/[indexKind]/[indexId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/index-quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/index-quality">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/index-quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/index-quality/query-audits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/index-quality/query-audits">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/index-quality/query-audits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/alerts">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/export-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/export-status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/export-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/readiness">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/slos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/slos">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/slos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/operations/timelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/timelines">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/operations/timelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/drills/[drillId]/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recovery/drills/[drillId]/evidence">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/drills/[drillId]/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/drills/[drillId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recovery/drills/[drillId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/drills/[drillId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/drills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recovery/drills">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/drills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recovery/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/findings/[findingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/findings/[findingId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/findings/[findingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/findings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/findings">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/findings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/risk-acceptances/[riskAcceptanceId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/risk-acceptances/[riskAcceptanceId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/risk-acceptances">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/approved-models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approved-models">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/approved-models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/activity">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/derivatives/[derivativeId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/derivatives/[derivativeId]/preview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/derivatives/[derivativeId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/derivatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/derivatives">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/derivatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/governance">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/ledger">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/manifest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/manifest">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/manifest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/overview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/governance/runs/[runId]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/ingest-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/ingest-status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/ingest-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/layout">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/layout/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/layout/workspace">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/preprocessing/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/preprocessing">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/preprocessing/quality">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/preprocessing/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocessing/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/privacy/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/privacy">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/privacy/workspace">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/transcription/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/transcription">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/transcription/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/transcription/workspace">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/viewer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/[documentId]/viewer">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/viewer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents/import">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/documents">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/entities/[entityId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/entities/[entityId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/entities/[entityId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/entities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/entities">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/entities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-candidates/[candidateId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-candidates/[candidateId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-candidates/[candidateId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-candidates">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/validation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/validation">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/validation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/verification">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/[bundleId]/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/bundles">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/bundles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/provenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/provenance">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/provenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/[exportRequestId]/reviews">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/[exportRequestId]/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests/new">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-requests">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/export-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export-review">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/export-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/derivative/[indexId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/indexes/derivative/[indexId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/derivative/[indexId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/entity/[indexId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/indexes/entity/[indexId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/entity/[indexId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/indexes">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/search/[indexId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/indexes/search/[indexId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/search/[indexId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/[jobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/[jobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/jobs">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/datasets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/model-assignments/[assignmentId]/datasets">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/datasets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/model-assignments/[assignmentId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/model-assignments">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/overview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/policies/[policyId]/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/policies/[policyId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/active/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/policies/active">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/active/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/policies">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/pseudonym-registry/[entryId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pseudonym-registry/[entryId]/events">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/pseudonym-registry/[entryId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/pseudonym-registry/[entryId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pseudonym-registry/[entryId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/pseudonym-registry/[entryId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/pseudonym-registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pseudonym-registry">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/pseudonym-registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/search">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error">> = Specific
  const handler = {} as typeof import("../../app/(public)/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../app/(public)/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(public)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logout">> = Specific
  const handler = {} as typeof import("../../app/(public)/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/capacity/tests/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/capacity/tests/run">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/capacity/tests/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/drills/[drillId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/recovery/drills/[drillId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/drills/[drillId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/recovery/drills/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/recovery/drills/run">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/recovery/drills/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/findings/[findingId]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/security/findings/[findingId]/accept">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/findings/[findingId]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/renew/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/security/risk-acceptances/[riskAcceptanceId]/renew">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/renew/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/review-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/security/risk-acceptances/[riskAcceptanceId]/review-schedule">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/review-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/security/risk-acceptances/[riskAcceptanceId]/revoke">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/security/risk-acceptances/[riskAcceptanceId]/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/approved-models/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/approved-models/create">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/approved-models/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/candidate-snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/derivatives/[derivativeId]/candidate-snapshots">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/derivatives/[derivativeId]/candidate-snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/document-imports/[importId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/document-imports/[importId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/document-imports/[importId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/document-imports/[importId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/document-imports/[importId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/document-imports/[importId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/pages">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/[runId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs/active">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout-runs">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/layout/overview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/layout/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/pages/[pageId]/image">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/pages/[pageId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/pages/[pageId]/variants">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/pages/[pageId]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages/[pageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages/[pageId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages/[pageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/rerun/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/rerun">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/rerun/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/active">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/preprocess-runs">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/pages/[pageId]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/pages/[pageId]/preview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/privacy/runs/[runId]/pages/[pageId]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/processing-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/[runId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/processing-runs/[runId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/[runId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/processing-runs">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/processing-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/retry-extraction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/retry-extraction">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/retry-extraction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/[lineId]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/lines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/tokens">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/variant-layers/NORMALISED/suggestions/[suggestionId]/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/variant-layers/NORMALISED/suggestions/[suggestionId]/decision">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/[pageId]/variant-layers/NORMALISED/suggestions/[suggestionId]/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/[runId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/active">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/decisions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/compare/decisions">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/decisions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/compare/finalize">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/compare">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/fallback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs/fallback">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/fallback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription-runs">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription/metrics">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription/overview">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/triage/pages/[pageId]/assignment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription/triage/pages/[pageId]/assignment">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/triage/pages/[pageId]/assignment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/triage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/[documentId]/transcription/triage">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/[documentId]/transcription/triage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/sessions/[sessionId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/chunks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/sessions/[sessionId]/chunks">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/chunks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/sessions/[sessionId]/complete">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/sessions">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/import/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/documents/import/upload">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/import/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/derivative/[indexId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/derivative/[indexId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/derivative/[indexId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/entity/[indexId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/entity/[indexId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/entity/[indexId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/rebuild/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/rebuild">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/rebuild/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/indexes/search/[indexId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/indexes/search/[indexId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/indexes/search/[indexId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/[jobId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/jobs/[jobId]/status">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/[jobId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/jobs/cancel">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/jobs/retry">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/jobs/run-noop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/jobs/run-noop">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/jobs/run-noop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/model-assignments/[assignmentId]/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/retire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/model-assignments/[assignmentId]/retire">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/[assignmentId]/retire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/model-assignments/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/model-assignments/create">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/model-assignments/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/[policyId]/activate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/retire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/[policyId]/retire">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/retire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/rollback-draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/[policyId]/rollback-draft">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/rollback-draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/[policyId]/update">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/[policyId]/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/[policyId]/validate">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/[policyId]/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/policies/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/policies/create">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/policies/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/search/open/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/search/open">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/search/open/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/settings/add-member/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/settings/add-member">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/settings/add-member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/settings/change-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/settings/change-role">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/settings/change-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/settings/remove-member/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[projectId]/settings/remove-member">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/settings/remove-member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/create">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/dev-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/dev-login">> = Specific
  const handler = {} as typeof import("../../app/auth/dev-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(authenticated)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/documents/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[projectId]/documents">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/documents/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(authenticated)/projects/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/(authenticated)/projects/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
