apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "ukde.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ukde.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "ukde.apiServiceAccountName" . }}
      automountServiceAccountToken: {{ .Values.services.api.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "ukde.image" (dict "root" . "service" .Values.services.api) | quote }}
          imagePullPolicy: {{ .Values.services.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.api.containerPort }}
              name: http
          env:
            - name: UKDE_API_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: UKDE_API_ENVIRONMENT
            {{- if .Values.storage.controlled.enabled }}
            - name: STORAGE_CONTROLLED_ROOT
              value: {{ .Values.storage.controlled.mountPath | quote }}
            {{- end }}
          {{- if .Values.storage.controlled.enabled }}
          volumeMounts:
            - name: controlled-storage
              mountPath: {{ .Values.storage.controlled.mountPath | quote }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
      {{- if .Values.storage.controlled.enabled }}
      volumes:
        - name: controlled-storage
          persistentVolumeClaim:
            claimName: {{ include "ukde.controlledStoragePvcName" . }}
      {{- end }}
