apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workers
  labels:
    {{- include "ukde.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.workers.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: workers
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ukde.labels" . | nindent 8 }}
        app.kubernetes.io/component: workers
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: workers
          image: {{ include "ukde.image" (dict "root" . "service" .Values.services.workers) | quote }}
          imagePullPolicy: {{ .Values.services.workers.image.pullPolicy }}
          env:
            - name: UKDE_WORKER_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: UKDE_WORKER_ENVIRONMENT
          resources:
            {{- toYaml .Values.resources.workers | nindent 12 }}

