{{- if and .Values.storage.controlled.enabled .Values.storage.controlled.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ukde.controlledStoragePvcName" . }}
  labels:
    {{- include "ukde.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.controlled.persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.controlled.persistentVolumeClaim.size | quote }}
  {{- if .Values.storage.controlled.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.storage.controlled.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
{{- end }}
