{{- if .Values.services.workers.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ukde.workersServiceAccountName" . }}
  labels:
    {{- include "ukde.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.services.workers.serviceAccount.automountServiceAccountToken }}
{{- end }}
