var R=require("../../../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(authenticated)/projects/[projectId]/documents/[documentId]/preprocess-runs/[runId]/activate/route.js")
R.c("server/chunks/[root-of-the-server]__04e039e1._.js")
R.c("server/chunks/web_lib_data_api-client_ts_e0ef38f9._.js")
R.c("server/chunks/web_lib_routes_ts_62a4279b._.js")
R.c("server/chunks/_a0e427fd._.js")
R.c("server/chunks/[root-of-the-server]__f3948257._.js")
R.c("server/chunks/web_lib_documents_ts_a2fa8b7f._.js")
R.c("server/chunks/8aa16_documents_[documentId]_preprocess-runs_[runId]_activate_route_actions_dc62e837.js")
R.m(40955)
module.exports=R.m(40955).exports
