var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(authenticated)/projects/[projectId]/documents/import/upload/route.js")
R.c("server/chunks/[root-of-the-server]__e73f177b._.js")
R.c("server/chunks/web_lib_data_api-client_ts_e0ef38f9._.js")
R.c("server/chunks/web_lib_routes_ts_62a4279b._.js")
R.c("server/chunks/_a0e427fd._.js")
R.c("server/chunks/[root-of-the-server]__f3948257._.js")
R.c("server/chunks/web_lib_documents_ts_a2fa8b7f._.js")
R.c("server/chunks/e194b_projects_[projectId]_documents_import_upload_route_actions_b9c6c5f1.js")
R.m(31690)
module.exports=R.m(31690).exports
