var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e27716b1._.js")
R.c("server/chunks/ssr/72a07_next_dist_36331c49._.js")
R.c("server/chunks/ssr/72a07_next_dist_esm_build_templates_app-page_97ce66e0.js")
R.c("server/chunks/ssr/[root-of-the-server]__8693bde8._.js")
R.c("server/chunks/ssr/72a07_next_dist_compiled_@opentelemetry_api_index_6b22eeda.js")
R.c("server/chunks/ssr/[root-of-the-server]__79f6759e._.js")
R.c("server/chunks/ssr/72a07_next_dist_esm_bc5c76c4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7262aa0b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ad9ec25e._.js")
R.c("server/chunks/ssr/web_app_error_tsx_b590f42d._.js")
R.c("server/chunks/ssr/_eb544ec7._.js")
R.c("server/chunks/ssr/_38ad4f78._.js")
R.c("server/chunks/ssr/web_lib_68bdc331._.js")
R.c("server/chunks/ssr/72a07_next_dist_client_components_3b1c11e6._.js")
R.c("server/chunks/ssr/web__next-internal_server_app__not-found_page_actions_9eaa9845.js")
R.m(95653)
module.exports=R.m(95653).exports
