var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b3a7a63f._.js")
R.c("server/chunks/ssr/72a07_next_dist_36331c49._.js")
R.c("server/chunks/ssr/72a07_next_dist_a4a5510c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8693bde8._.js")
R.c("server/chunks/ssr/72a07_next_dist_compiled_@opentelemetry_api_index_6b22eeda.js")
R.c("server/chunks/ssr/[root-of-the-server]__79f6759e._.js")
R.c("server/chunks/ssr/72a07_next_dist_esm_bc5c76c4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7262aa0b._.js")
R.c("server/chunks/ssr/web__next-internal_server_app__global-error_page_actions_2a1e94d4.js")
R.m(94305)
module.exports=R.m(94305).exports
